//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produkty()
        {
            this.PozycjeFaktury = new HashSet<PozycjeFaktury>();
            this.PozycjeZamowienia = new HashSet<PozycjeZamowienia>();
            this.StanyMagazynowe = new HashSet<StanyMagazynowe>();
            this.Zwroty = new HashSet<Zwroty>();
        }
    
        public int IdProduktu { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> IdDostawcy { get; set; }
        public Nullable<int> IdKategorii { get; set; }
        public Nullable<decimal> CenaZakupu { get; set; }
        public Nullable<decimal> CenaSprzedazy { get; set; }
        public Nullable<decimal> Ilosc { get; set; }
    
        public virtual DostawcyProduktow DostawcyProduktow { get; set; }
        public virtual Kategorie Kategorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjeFaktury> PozycjeFaktury { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjeZamowienia> PozycjeZamowienia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StanyMagazynowe> StanyMagazynowe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zwroty> Zwroty { get; set; }
    }
}
