//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StanyMagazynowe
    {
        public int IdStanuMagazynowego { get; set; }
        public Nullable<int> IdMagazynu { get; set; }
        public Nullable<int> IdProduktu { get; set; }
        public Nullable<decimal> Ilosc { get; set; }
    
        public virtual Magazyny Magazyny { get; set; }
        public virtual Produkty Produkty { get; set; }
    }
}
