//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zwroty
    {
        public int IdZwrotu { get; set; }
        public Nullable<int> IdProduktu { get; set; }
        public Nullable<int> IdFaktury { get; set; }
        public Nullable<System.DateTime> DataZwrotu { get; set; }
        public Nullable<decimal> Ilość { get; set; }
    
        public virtual Faktury Faktury { get; set; }
        public virtual Produkty Produkty { get; set; }
    }
}
